apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres-postgresql.default.svc.cluster.local:5432/server"
  JWT_SECRET: "ZAGLUSHKA"
